# If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
#
# Find the sum of all the multiples of 3 or 5 below 1000.
#

count = 0

for i in range(1,1000):
  if i % 3 == 0:
    count = count + i
  elif i % 5 == 0:
    count = count + i

print(count)


# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
even = []

def fib(n):
 a,b = 1,1
 for i in range(n):
  a,b = b,a+b
  if a % 2 == 0:
    even.append(a)

fib(10)
print(sum(even))


# The prime factors of 13195 are 5, 7, 13 and 29.
#
# What is the largest prime factor of the number 600851475143 ?

n = 600851475143
i = 2

while i * i < n:
    while n % i == 0:
        n = n / i
    i = i + 1
print(n) 
